apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loxilb-peer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: loxilb-peer-app
  template:
    metadata:
      name: loxilb-peer
      labels:
        app: loxilb-peer-app
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.loxilbPeer.affinity}}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: loxilb-peer-app
        image: {{ .Values.loxilbPeer.image }}
        command: [ "/root/loxilb-io/loxilb/loxilb", "--peer" ]
        ports:
        - containerPort: {{ .Values.loxilbPeer.ports.apiserver }}
        - containerPort: {{ .Values.loxilbPeer.ports.bgp }}
        - containerPort: {{ .Values.loxilbPeer.ports.gobgp }}
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: loxilb-peer-service
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: loxilb-peer-app
  ports:
  - name: loxilb-peer-api
    port: {{ .Values.loxilbPeer.ports.apiserver }}
    targetPort: {{ .Values.loxilbPeer.ports.apiserver }}
    protocol: TCP
  - name: loxilb-peer-bgp
    port: {{ .Values.loxilbPeer.ports.bgp }}
    targetPort: {{ .Values.loxilbPeer.ports.bgp }}
    protocol: TCP
  - name: loxilb-peer-gobgp
    port: {{ .Values.loxilbPeer.ports.gobgp }}
    targetPort: {{ .Values.loxilbPeer.ports.gobgp }}
    protocol: TCP


